### ISSUE TITLE
for approval

### ISSUE THREAD

**Issue by pratap-panabaka** [PRATAP-KUMAR/book-an-appointment#13]
Hello code reviewer, good day

We are 5 in the group

1. @Amtresu 
2. @itsmraga-hub
3. @Kwaleyela-Ikafa
4. @PRATAP-KUMAR
5. @David-Kasilia

Link to the project - https://github.com/users/PRATAP-KUMAR/projects/3

### Screenshot of Kanbanboard
![Screenshot from 2023-01-04 19-35-57](https://user-images.githubusercontent.com/40719899/210572649-69ff848f-bb24-47f6-8754-8d0b4c6b6fc3.png)

### GIF image showing Kanbanboard

![1](https://user-images.githubusercontent.com/40719899/210572777-c98cb0bd-0ce5-4606-b4c1-7ec6dffeccf6.gif)

**Comment by Meltrust** [comment]
Hi @PRATAP-KUMAR,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by pratap-panabaka** [comment]
@Meltrust Thank you for pointing out those and I have added them now. I am going to raise a new Request. Thank You.

**Comment by Meltrust** [comment]
Hi STUDENT_MENTION

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks are pointed fairly, all tasks assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

According to the project requirements:

![image](https://user-images.githubusercontent.com/57421823/210574968-25d807c9-fc66-4243-93d8-b5fff5d7e3c3.png)


However, this is not a task, and it does not have points:

![image](https://user-images.githubusercontent.com/57421823/210574377-cb32b950-a04c-43da-994b-4498376cd6c1.png)

Therefore:

- [x] Kindly remove that card for the purposes of this project/review.  Since it is not a task that can be assigned, it does not have points, making it impossible to comply with the requirement.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by pratap-panabaka** [comment]
@Meltrust Thank you for your comments to help us with Kanbanboard, Changes are done. I am submitting it for review. Thank You.

**Comment by Meltrust** [comment]
Hi @PRATAP-KUMAR,,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All tasks now have pointings ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by pratap-panabaka** [comment]
@Meltrust Thank you very much for pushing me towards this project approval. I am very thankful to code reviewers like you.
